### PR TITLE
Bump karma from 4.4.1 to 5.2.3

### PR DESCRIPTION
**Pull request by phil-davis**
Bumps [karma](https://github.com/karma-runner/karma) from 4.4.1 to 5.2.3.
- [Release notes](https://github.com/karma-runner/karma/releases)
- [Changelog](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md)
- [Commits](https://github.com/karma-runner/karma/compare/v4.4.1...v5.2.3)

Signed-off-by: dependabot-preview[bot] <support@dependabot.com>

This is a cherry-pick from PR #891 - drone CI is not starting there.

### CODE REVIEW

**Comment by phil-davis** [comment]
Note: the original commit is from dependabot-preview and GitHub is too stupid and thinks that a bot somehow needs to sign the CLA.

**Comment by mmattel** [comment]
node should be upgraded...
```
The engine "node" is incompatible with this module. Expected version ">= 10". Got "8.17.0"
```

**Comment by phil-davis** [comment]
Rebased. Let's see what CI thinks.

**Comment by mmattel** [comment]
still: `The engine "node" is incompatible with this module. Expected version ">= 10". Got "8.17.0"`
@LukasHirt has created https://github.com/owncloud-ci/nodejs/pull/7 (Add node version 12, merged), but I guess that due to the parametrisation of docker here, it is not used...
This is ihmo true for other repos too, I may be wrong, just my thoughts

**Comment by phil-davis** [comment]
The node version in CI has been fixed in PR #910 - after that is merged, I can rebase here and move forward.

**Comment by phil-davis** [comment]
Rebased...

**Comment by JanAckermann** [comment]
@micbar can be merged ?

**Comment by phil-davis** [comment]
Rebased to get up-to-date CI. @micbar merge?

**Review by micbar — APPROVED** [review]

**Comment by micbar** [comment]
merge conflict

**Comment by JanAckermann** [comment]
@micbar resolved

**Pull request merged**
