### PR TITLE
Chunk deleting of rows from the activity table

### PR DESCRIPTION
**Pull request by tomneedham**
Fixes for clustered environments, which have a limit on rows and size of data affected by each transaction due to replication concerns.

### CODE REVIEW

**Comment by tomneedham** [comment]
Need to test this manually as well - WIP

**Comment by tomneedham** [comment]
So it turns out postgres, sqlite and oracle all don't like limits in their delete statements.

**Comment by GrendelWWU** [comment]
Hello Tom. 
I really like that. Can I apply this patch to 10.0.4?

**Comment by tomneedham** [comment]
This will apply on top of v2.3.6 and will appear in the marketplace pending QA

**Comment by madsi1m** [comment]
Hi can this please be added to stable10?

**Comment by DeepDiver1975** [comment]
Grab version  2.3.7 from the marketplace - this holds this change

**Pull request merged**
