### PR TITLE
Fix grouping for share messages

### PR DESCRIPTION
**Pull request by PVince81**
Retry after https://github.com/owncloud/activity/pull/624

### CODE REVIEW

**Comment by PVince81** [comment]
Fixes #613

**Comment by jvillafanez** [comment]
Code looks good although I don't have enough context to evaluate the solution.

Is the grouping key stored somewhere (in case we need a migration for the `getGroupKey` change)?

**Comment by PVince81** [comment]
@jvillafanez the key is not stored. The grouping is done on the fly whenever an activity is being added to the collection. Later on within the same PHP request we call `$groupHelper->getActivities()` to retrieve the result.

**Comment by PVince81** [comment]
weird, that worked locally:
```
) OCA\Activity\Tests\GroupHelperTest::testAddActivity with data set #6 (array(2, array('param'), array('messageparams'), 1444895509, 7, 'file2'), array(Mock_IParameter_ddbc587a Object (...)), array(5, array('param'), array('messageparams'), 1444895510, array(Mock_Collection_3197f96d Object (...)), array(), array(5, 4, 3), 42, array('file5', 'file4', 'file3')), 'same', 'same', array(), array(5, array('param'), array('messageparams'), 1444895510, array(Mock_Collection_3197f96d Object (...)), array(), array(5, 4, 3, 2), 42, array('file5', 'file4', 'file3', 'file2')))
json_decode() expects parameter 1 to be string, array given
/home/travis/build/owncloud/core/apps/activity/lib/GroupHelper.php:115
/home/travis/build/owncloud/core/apps/activity/tests/GroupHelperTest.php:509
```

**Comment by PVince81** [comment]
Turns out I pushed the wrong branch :frowning:

**Comment by PVince81** [comment]
correct PR here: https://github.com/owncloud/activity/pull/626

**Pull request closed without merging**
