### PR TITLE
[stable10] Dont try to delete items when no users in context

### PR DESCRIPTION
**Pull request by tomneedham**
Backport of https://github.com/owncloud/activity/pull/604 to stable10

### CODE REVIEW

**Comment by PVince81** [comment]
codecov not happy, need unit test update

**Comment by tomneedham** [comment]
This does not make sense / have any effect until https://github.com/owncloud/activity/pull/574 is backported

**Comment by tomneedham** [comment]
And requires the new tests from the original PR

**Comment by tomneedham** [comment]
@ownclouders rebase

**Comment by tomneedham** [comment]
closing as I made new fixes in the upstream branch

**Pull request closed without merging**
