### PR TITLE
Absolute URLs are generated incorrectly

### LINKED ISSUE #508: wrong links in RSS feed
When a user User has created a file foo/bar.txt , the activity rss feed notes (German locale):

User hat foo/bar-txt erstellt

with a link target to https://server.net/owncloud/files/index.php?dir=/foo , which however should be https://server.net/owncloud/index.php/apps/files/?dir=/foo .

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #508 

@rabauke Can you test this?

It will only work for new entries thou :(

### CODE REVIEW

**Comment by karlitschek** [comment]
looks good 👍

**Comment by rabauke** [comment]
This works perfectly! Thanks for the prompt fix.

**Comment by rullzer** [comment]
:+1:

**Comment by nickvergessen** [comment]
@karlitschek should backport to 9.0

**Comment by karlitschek** [comment]
please backport

**Pull request merged**
