### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by phil-davis**
While doing `Makefile` refactoring I noticed that this repo has no `LICENSE` file.

I copied this one from another public app repo.

### CODE REVIEW

**Comment by PVince81** [comment]
we should script this and push it to all repos

**Comment by phil-davis** [comment]
There are quite a lot of public app repos without a `LICENSE` file. I guess they should all be the same - GPL v2 or v3?

**Comment by phil-davis** [comment]
I raised issue https://github.com/owncloud/QA/issues/610 to address the general problem across apps.
@PVince81 close this for now? For approve and merge?

**Comment by PVince81** [comment]
please close, it's the wrong license anyway, see https://github.com/owncloud/activity/blob/master/appinfo/info.xml#L16

**Pull request closed without merging**
