### PR TITLE
[stable9.1] fix 529: Avatar image in activity tab broken for "remote user"

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/activity/pull/530 to stable9.1

@DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
@DeepDiver1975 looks like travis needs some massage here:
```php build/composer.phar install --dev

You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug

You are using the deprecated option "dev". Dev packages are installed by default now.

Loading composer repositories with package information

Installing dependencies (including require-dev) from lock file

Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

Your requirements could not be resolved to an installable set of packages.

  Problem 1

    - Installation request for doctrine/cache v1.6.0 -> satisfiable by doctrine/cache[v1.6.0].

    - doctrine/cache v1.6.0 requires php ~5.5|~7.0 -> your PHP version (5.4.45) does not satisfy that requirement.

  Problem 2

    - Installation request for doctrine/common v2.6.1 -> satisfiable by doctrine/common[v2.6.1].

    - doctrine/common v2.6.1 requires php ~5.5|~7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
...
```

**Comment by PVince81** [comment]
failing tests unrelated btw

**Comment by PVince81** [comment]
moving to 9.1.3

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 looks like travis needs some massage here:

yes - the master script to install owncloud does not work for any stable release - https://github.com/owncloud/activity/blob/stable9.1/.travis.yml#L21

**Comment by PVince81** [comment]
so... how to fix it ? do we use the old version of the script if there was one ?

**Comment by PVince81** [comment]
Blocked by https://github.com/owncloud/activity/issues/548

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
