### PR TITLE
Start activities for renames

### LINKED ISSUE #375: File and folder renames do not show up as activity
This should be the case though, as:

> `Username` renamed **oldfilename.txt** to **newfilename.txt**

@nickvergessen

### PR DESCRIPTION
**Pull request by nickvergessen**
### Todo
- [x] If someone renames a shared item, we shouldn't trigger activities for the owner and others, just for the current user
- [x] Requires #449
- [ ] Moving

Fix #375

### CODE REVIEW

**Comment by karlitschek** [comment]
good :+1:

**Comment by MorrisJobke** [comment]
Moving this to 9.1 because the issue was moved too.

**Comment by jancborchardt** [comment]
What’s the progress here @nickvergessen?

Also cc @alvar-freude for testing cause you commented on https://github.com/owncloud/activity/issues/375

**Comment by nickvergessen** [comment]
Not ready yet, it has issues currently, when someone renames a folder that was shared with you, you still see the activity, although the name didn't change for you.

**Pull request closed without merging**
