### PR TITLE
Modify checkboxes to work with new style

### PR DESCRIPTION
**Pull request by Henni**
required for owncloud/core#18735

### CODE REVIEW

**Comment by jancborchardt** [comment]
:+1: @Henni you get a drink tomorrow at the meetup!

**Comment by nickvergessen** [comment]
I can't really see a difference?

I assume this is for https://github.com/owncloud/core/pull/18735 ?
I checked that out and rebased it locally, but that doesn't work very well then:

personlich_-_owncloud_-_2015-09-16_00 10 44

**Comment by jancborchardt** [comment]
@nickvergessen you clearly don’t have the latest version of https://github.com/owncloud/core/pull/18735 – the checked checkboxes are slightly blue.

**Comment by jancborchardt** [comment]
This is how it looks like:
capture du 2015-09-16 00-14-06

**Comment by jancborchardt** [comment]
This is how it looks like:
capture du 2015-09-16 00-14-51

**Comment by nickvergessen** [comment]
Right, reset my branch now it looks like that.
I don't think it looks prettier, but at least it still also works, so fine by me.

**Pull request merged**
