### PR TITLE
Migrate to bigint

### PR DESCRIPTION
**Pull request by VicDeo**
Ref https://github.com/owncloud/core/issues/26901
- [x] Depends on https://github.com/owncloud/core/pull/28364 (PostgreSQL will fail otherwise)

### CODE REVIEW

**Comment by felixboehm** [comment]
@VicDeo are you working on this? Please assign or let me know blockers ...

**Comment by VicDeo** [comment]
@felixboehm in fact it is already done. Needs https://github.com/owncloud/core/pull/28364 to pass the tests on postgresql

**Comment by DeepDiver1975** [comment]
So we need to be very carefull with merging this - if this requires core changes we need to increment the apps min depecndency to 10.0.3 - if we backport owncloud/core#28364 to 10.0.3

**Comment by felixboehm** [comment]
Can we release activity app now, and another version containing this fix with 10.0.3?

**Comment by DeepDiver1975** [comment]
> Can we release activity app now, and another version containing this fix with 10.0.3?

yes

**Comment by PVince81** [comment]
>  if this requires core changes 

I don't think this requires core changes. We don't have any foreign keys or anything...

@VicDeo can you confirm ?

**Comment by VicDeo** [comment]
@PVince81 this migration will fail on postgresql without a patch from https://github.com/owncloud/core/pull/28364

**Comment by VicDeo** [comment]
Rebased to test on top of the current master

**Comment by DeepDiver1975** [comment]
min oc version has to be 10.0.3

**Comment by VicDeo** [comment]
@DeepDiver1975 done

**Comment by VicDeo** [comment]
@DeepDiver1975 dependencies are resolved: https://github.com/owncloud/core/pull/28364 is merged into master/stable10. 
Anything else needed from my side to get this in?

**Comment by PVince81** [comment]
@VicDeo I suggest for core 10.0.3 beta to be out before merging. If we merge this then the activity app will not work at all with the core repo due to version mismatch.

**Comment by PVince81** [comment]
10.0.3 beta has been built (pending announcement)

Merge?

**Comment by PVince81** [comment]
@DeepDiver1975 @VicDeo needs review / decision.

I think we can already merge this. People checking out stable10 from git will get the correct version so the activity app from git will work. Once we release to app store, only people with 10.0.3 will see this release. So at no point will there be breakage.

**Comment by PVince81** [comment]
no backport needed, activity is released to the market from master

**Pull request merged**
