### PR TITLE
fixes #632 - query parameter for preview generation was missing

### LINKED ISSUE #632: Previews of text files are not shown in activity menu when we create, share, edit... a text file
### Steps to reproduce
1. Create a text file
2. Share it with a user
3. Go to activity section

### Expected behaviour
Text files previews should be shown

### Actual behaviour
Text files previews are not shown

### Server configuration

oC 10.0.9.RC3 and activity branch release-2.3.7

### Client configuration
**Safari:**
screen shot 2018-07-10 at 08 55 43

**Chrome:**

screen shot 2018-07-10 at 08 56 51

**Operating system:**
Ubuntu 16.04

### Logs

No relevant info shown in the browser console, network tab or the server logs

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by davitol** [comment]
👍 Tested and works

**Comment by davitol** [comment]
@DeepDiver1975 with the current PR now the thumbnails of text files are shown, but if we delete the file (move to trashbin) the preview is no longer shown. It is a different behavior from what happens with image files

**Creating a text file**
screen shot 2018-07-10 at 12 30 43

**Deleting a text file**

screen shot 2018-07-10 at 12 31 41

**Comment by DeepDiver1975** [comment]
I'll have a look ....

**Comment by davitol** [comment]
Let's merge this PR and follow up this stuff in other issue: https://github.com/owncloud/activity/issues/635

**Pull request merged**
