### PR TITLE
 files/folders in html emails are now clickable

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Fixes https://jira.owncloud.com/browse/OC-2285

## Screenshot

Screenshot_2020-10-14 MailHog

### Url Format
`<a href="http://localhost/index.php/f/127">Screenshot_2020-02-26 Document Classification app ownCloud marketplace.png</a>`

### CODE REVIEW

**Comment by micbar** [comment]
@DeepDiver1975 Thanks.

I see that you create the links to the owncloud page.
In the concept we thought about using the private link.

**Comment by DeepDiver1975** [comment]
> I see that you create the links to the owncloud page.
> In the concept we thought about using the private link.

The problem is that I don't have the private link at hand at this point in time ..... 
..... I can do some more refactoring if this is a must have - which might cause some :boom:

**Comment by micbar** [comment]
@DeepDiver1975 So far so good.
Tested it, works.

**Comment by DeepDiver1975** [comment]
> ..... I can do some more refactoring if this is a must have - which might cause some boom

no refactoring was necessary - just some :unicorn: dust ...

**Comment by micbar** [comment]
Regex unicorn power

**Review by micbar — APPROVED** [review]
LGTM

**Pull request merged**
