### PR TITLE
Use permalinks in activities

### PR DESCRIPTION
**Pull request by PVince81**
- [x] REQUIRES: permalinks in core https://github.com/owncloud/core/pull/24434
- [ ] TODO: fix unit tests
- [x] TODO: trashbin cases ? (might be a job for core...)
- [ ] TEST: all three cases, especially the one with "getInfoByPath" where we get the fileid from `$info`

Are there other cases I forgot ?

### CODE REVIEW

**Comment by nickvergessen** [comment]
Well since it doesn't work for trashbin and the old way does, I'd say we shouldn't do that atm:
https://github.com/owncloud/core/pull/24434#discussion_r62339111

**Comment by PVince81** [comment]
- [ ] REQUIRES: https://github.com/owncloud/core/pull/24537 for trash support

**Comment by PVince81** [comment]
doesn't work, needs rework, no time

**Comment by PVince81** [comment]
rebased

**Comment by PVince81** [comment]
not a priority currently and there are technical challenges that will take longer to solve.
activity app concept needs to be rethought on a higher level

**Pull request closed without merging**
