### PR TITLE
[tests-only] [full-ci] Test acceptance fail 20210706

### PR DESCRIPTION
**Pull request by phil-davis**
On top of #983 

Purposely make a scenario fail, to test that the early-fail and GitHub comment code works in `.drone.star`

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiActivity-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/activity/2012/25/1

**Comment by phil-davis** [comment]
Failed as expected, GitHub comment was posted, the other pipelines were cancelled.

**Comment by phil-davis** [comment]
Now testing with `full-ci` to see the result.

**Comment by phil-davis** [comment]
full-ci ran all pipelines, and 1 of them failed as expected. Good.

**Pull request closed without merging**
