### PR TITLE
use new checkbox style for in-app settings

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @nickvergessen @Henni @owncloud/designers 

We should also backport this since the new checkboxes should be used for 8.2 everywhere. @karlitschek

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by nickvergessen** [comment]
Backport shouldn't hurt, but is also not that strongly visible, so no need to kill kittens for bringing it in 8.2.1, can simply do it after that.

**Comment by karlitschek** [comment]
please backport :+1:

**Comment by jancborchardt** [comment]
Backported 1a75902

**Comment by nickvergessen** [comment]
Please always use branches for backports in the future

**Comment by jancborchardt** [comment]
@nickvergessen ok, sorry – thought we only use that workflow for core already. Will do in the future.

**Pull request merged**
