### PR TITLE
Fix unit tests partly

### PR DESCRIPTION
**Pull request by nickvergessen**
Caused by owncloud/core#18839 and the parents

### CODE REVIEW

**Comment by nickvergessen** [comment]
@Xenopathic please tell me how to fix this without app-dependency:
```
There were 4 errors:

1) OCA\Activity\Tests\ApiTest::testGet with data set #0 ('activity-api-user2', 0, 30, array())
OCP\AutoloadNotAllowedException: Autoload path not allowed: /home/travis/build/owncloud/core/apps/files/lib/activity.php

/home/travis/build/owncloud/core/lib/autoloader.php:134
/home/travis/build/owncloud/core/lib/autoloader.php:154
/home/travis/build/owncloud/core/lib/private/activitymanager.php:254
/home/travis/build/owncloud/core/apps/activity/lib/data.php:77
/home/travis/build/owncloud/core/apps/activity/lib/usersettings.php:110
/home/travis/build/owncloud/core/apps/activity/lib/data.php:187
/home/travis/build/owncloud/core/apps/activity/lib/api.php:46
/home/travis/build/owncloud/core/apps/activity/tests/apitest.php:169

2) OCA\Activity\Tests\ApiTest::testGet with data set #1 ('activity-api-user1', 0, 30, array(array('link', 'file', null, null, '', 'Subject2 @User #A/B.txt'), array('link', 'file', null, null, '', 'Subject1 #A/B.txt')))
OCP\AutoloadNotAllowedException: Autoload path not allowed: /home/travis/build/owncloud/core/apps/files/lib/activity.php

[Stacktrace]

3) OCA\Activity\Tests\ApiTest::testGet with data set #2 ('activity-api-user1', 0, 1, array(array('link', 'file', null, null, '', 'Subject2 @User #A/B.txt')))
OCP\AutoloadNotAllowedException: Autoload path not allowed: /home/travis/build/owncloud/core/apps/files/lib/activity.php

[Stacktrace]

4) OCA\Activity\Tests\ApiTest::testGet with data set #3 ('activity-api-user1', 1, 1, array(array('link', 'file', null, null, '', 'Subject1 #A/B.txt')))
OCP\AutoloadNotAllowedException: Autoload path not allowed: /home/travis/build/owncloud/core/apps/files/lib/activity.php

[Stacktrace]

```

**Comment by MorrisJobke** [comment]
Shouldn't `files` app be loaded anyway? Or do I miss something?

**Comment by nickvergessen** [comment]
Appearantly not in unit tests
Adding
```php
\OC_App::loadApp('files');
```
helps, then I get 
> OCP\AutoloadNotAllowedException: Autoload path not allowed: /home/nickv/ownCloud/master/core/apps/files_sharing/lib/activity.php

So I add 
```php
\OC_App::loadApp('files_sharing');
```

Then I get 
```json
{"reqId":"xwlDchlPdp4X3HlQbgw1","remoteAddr":"","app":"files_versions","message":"Could not find resource file \"\/apps\/files_versions\/js\/versions.js\"","level":3,"time":"2015-09-07T08:06:10+00:00"}
```

So I add 
```php
\OC_App::loadApp('files_versions');
```

.........

Note: I never told anyone to load any of those files directly. I just grab the activity manager to replace it with a mock and restore it afterwards. But grabbing executes that stuff.
The apps register their code in app.php so it is executed, afterwards the classes can not be loaded due to the path restriction.

**Comment by MorrisJobke** [comment]
@nickvergessen Thanks for the explanation. I think this is something we need to look into with the new app loader.

**Pull request merged**
