### PR TITLE
Merge pull request #25 from nextcloud/identify-remote-users-by-token

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Try to identify remote users by their token

### CODE REVIEW

**Comment by nickvergessen** [comment]
:-1: Yo mister, what do you think about copyright violations?

**Comment by MorrisJobke** [comment]
> 👎 Yo mister, what do you think about copyright violations?

Calm down... this is not a copyrigth violation.

**Comment by DeepDiver1975** [comment]
> what do you think about copyright violations?

If you explain me where any violation did happen I happily discuss ...

**Comment by nickvergessen** [comment]
Well it's great for your community users when you take my AGPL contributions, since they receives more fixes and features. But also sad that you don't want to include the app for your customers anymore.

**Comment by DeepDiver1975** [comment]
Why should customers not get these changes?

**Comment by nickvergessen** [comment]
Because the AGPL is incompatible with your commercial license?

Anyway I'm out of this

**Pull request closed without merging**
