### PR TITLE
replace deprecated config calls with proper method calls

### PR DESCRIPTION
**Pull request by MorrisJobke**
Ref owncloud/core#12260

### CODE REVIEW

**Comment by MorrisJobke** [comment]
See https://github.com/owncloud/core/blob/master/lib/private/preferences.php#L132

**Comment by Raydiation** [comment]
What about also killing legacy OC_Preferences? Only usage is in lib/private/installer.php but im only using core + calendar + news + notes + contacts

**Comment by MorrisJobke** [comment]
@Raydiation https://github.com/owncloud/core/pull/13869 ;)

**Comment by nickvergessen** [comment]
will merge, as soon as stable8 branches are created

**Pull request merged**
