### PR TITLE
Correctly generate links around the preview with scrollto= parameter

### LINKED ISSUE #310: clicking a document in the root opens it like a folder
clicking a document in the root creates a weird situation... See this video below!
bug

# steps to reproduce
1. go to Activity app
2. click a document residing in the /
3. watch how it is treated as a folder

This happens on daily oC 8.1 snapshot from yesterday, apache, Linux, MariaDB.

Possibly relevant log lines:
```
{"reqId":"8bMuKXItxQlMf4fJbC9v","remoteAddr":"::1","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/srv\/www\/htdocs\/owncloud\/data\/rosaparks\/avatar.png","level":0,"time":"2015-06-24T08:47:03+00:00","method":"GET","url":"\/owncloud\/index.php\/avatar\/rosaparks\/25.07462763786316?requesttoken=TNMpiqrmlm%2BBpbhL94vP6rUq3j2JP9"}
{"reqId":"kbMVt6DRjK7W92oTNUjx","remoteAddr":"::1","app":"PHP","message":"mime_content_type(\/Upload folder for friends): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/type\/detection.php#120","level":3,"time":"2015-06-24T08:47:03+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/activity\/activities\/fetch?filter=all&page=2"}
{"reqId":"kbMVt6DRjK7W92oTNUjx","remoteAddr":"::1","app":"PHP","message":"mime_content_type(\/Upload folder for friends): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/type\/detection.php#120","level":3,"time":"2015-06-24T08:47:03+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/activity\/activities\/fetch?filter=all&page=2"}
{"reqId":"kbMVt6DRjK7W92oTNUjx","remoteAddr":"::1","app":"PHP","message":"mime_content_type(\/Upload folder for friends): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/type\/detection.php#120","level":3,"time":"2015-06-24T08:47:03+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/activity\/activities\/fetch?filter=all&page=2"}
{"reqId":"kbMVt6DRjK7W92oTNUjx","remoteAddr":"::1","app":"PHP","message":"mime_content_type(\/Upload folder for friends): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/type\/detection.php#120","level":3,"time":"2015-06-24T08:47:03+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/activity\/activities\/fetch?filter=all&page=2"}
{"reqId":"kbMVt6DRjK7W92oTNUjx","remoteAddr":"::1","app":"PHP","message":"mime_content_type(\/Upload folder for friends): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/type\/detection.php#120","level":3,"time":"2015-06-24T08:47:03+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/activity\/activities\/fetch?filter=all&page=2"}
{"reqId":"kbMVt6DRjK7W92oTNUjx","remoteAddr":"::1","app":"PHP","message":"mime_content_type(\/Upload folder for friends): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/type\/detection.php#120","level":3,"time":"2015-06-24T08:47:03+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/activity\/activities\/fetch?filter=all&page=2"}
{"reqId":"tyjultYd2I4YchXd4v8t","remoteAddr":"::1","app":"files_locking","message":"INFO: Read lock requested for \/srv\/www\/htdocs\/owncloud\/data\/RosaLuxemburg\/avatar.jpg","level":0,"time":"2015-06-24T08:47:05+00:00","method":"GET","url":"\/owncloud\/index.php\/avatar\/RosaLuxemburg\/32?requesttoken=TNMpiqrmlm%2BBpbhL94vP6rUq3j2JP9"}
```
```
{"reqId":"rbYFMcLsOfDg9QDIvqZU","remoteAddr":"::1","app":"PHP","message":"mime_content_type(\/my public upload folder): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/type\/detection.php#120","level":3,"time":"2015-06-24T08:47:15+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/activity\/activities\/fetch?filter=all&page=1"}
{"reqId":"rbYFMcLsOfDg9QDIvqZU","remoteAddr":"::1","app":"PHP","message":"mime_content_type(\/my public upload folder): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/type\/detection.php#120","level":3,"time":"2015-06-24T08:47:15+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/activity\/activities\/fetch?filter=all&page=1"}
{"reqId":"rbYFMcLsOfDg9QDIvqZU","remoteAddr":"::1","app":"PHP","message":"mime_content_type(\/Upload folder for friends): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/type\/detection.php#120","level":3,"time":"2015-06-24T08:47:15+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/activity\/activities\/fetch?filter=all&page=1"}
{"reqId":"rbYFMcLsOfDg9QDIvqZU","remoteAddr":"::1","app":"PHP","message":"mime_content_type(\/Upload folder for friends): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/type\/detection.php#120","level":3,"time":"2015-06-24T08:47:15+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/activity\/activities\/fetch?filter=all&page=1"}
{"reqId":"gDWm4y3oL77fJGttAKpk","remoteAddr":"::1","app":"files_locking","message":"INFO: Read lock requested for \/srv\/www\/htdocs\/owncloud\/data\/rosaparks\/avatar.png","level":0,"time":"2015-06-24T08:47:15+00:00","method":"GET","url":"\/owncloud\/index.php\/avatar\/rosaparks\/25.07462763786316?requesttoken=TNMpiqrmlm%2BBpbhL94vP6rUq3j2JP9"}
```

```
{"reqId":"RymohAoOJHJfZYR+Rs5Q","remoteAddr":"::1","app":"PHP","message":"mime_content_type(\/my public upload folder): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/type\/detection.php#120","level":3,"time":"2015-06-24T08:45:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/activity\/activities\/fetch?filter=all&page=1"}
{"reqId":"RymohAoOJHJfZYR+Rs5Q","remoteAddr":"::1","app":"PHP","message":"mime_content_type(\/my public upload folder): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/type\/detection.php#120","level":3,"time":"2015-06-24T08:45:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/activity\/activities\/fetch?filter=all&page=1"}
{"reqId":"RymohAoOJHJfZYR+Rs5Q","remoteAddr":"::1","app":"PHP","message":"mime_content_type(\/Upload folder for friends): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/type\/detection.php#120","level":3,"time":"2015-06-24T08:45:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/activity\/activities\/fetch?filter=all&page=1"}
{"reqId":"RymohAoOJHJfZYR+Rs5Q","remoteAddr":"::1","app":"PHP","message":"mime_content_type(\/Upload folder for friends): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/type\/detection.php#120","level":3,"time":"2015-06-24T08:45:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/activity\/activities\/fetch?filter=all&page=1"}
{"reqId":"q2yveX2mMV1k\/Z1O+69b","remoteAddr":"::1","app":"files_locking","message":"INFO: Read lock requested for \/srv\/www\/htdocs\/owncloud\/data\/RosaLuxemburg\/avatar.jpg","level":0,"time":"2015-06-24T08:45:56+00:00","method":"GET","url":"\/owncloud\/index.php\/avatar\/RosaLuxemburg\/114.62686920166016?requesttoken=TNMpiqrmlm%2BBpbhL94vP6rUq3j2JP9"}
```

Let me know if you need anything more.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #310 

@jospoortvliet mind testing ;)

Otherwise @MorrisJobke

### CODE REVIEW

**Comment by jospoortvliet** [comment]
will test at home, don't have an install at the office.

**Comment by jospoortvliet** [comment]
Yes, this fixes the problem, @nickvergessen 

Thanks ;-)

**Comment by jospoortvliet** [comment]
I clicked around a bit and saw no new problems. I did find something you can discuss whether it is a problem or not: if you move a file to another folder, the link in Activity app doesn't update so it links to a folder which no longer has the file... Not sure if that can even be dealt with...

**Comment by nickvergessen** [comment]
No, we can not deal with that atm, but its on the backlog to try to find a way for that.

**Comment by jospoortvliet** [comment]
ok. not a big deal if you ask me, so backlog seems fine ;-)

**Comment by nickvergessen** [comment]
> ok. not a big deal if you ask me, so backlog seems fine ;-)

Just to make sure, in case someone else reads this, its something that needs changing in core, related:
https://github.com/owncloud/core/issues/11732

**Pull request merged**
