### PR TITLE
Add a config option to send notifications ASAP

### PR DESCRIPTION
**Pull request by VicDeo**
- Add a config option to send email notifications ASAP 
IRL it happens on the next `occ system:cron` invocation

### CODE REVIEW

**Comment by VicDeo** [comment]
@micbar 
It turned out to be simple.
what do you think on this approach?

**Comment by micbar** [comment]
@VicDeo Nice!

Coulsd you provide a screenshot?

Can we change the order of the list options? Currently it is from top to bottom, starting with the smallest interval.
In that logic, "As soon as possible" would be at the top.

@pmaier1 Fine for you? Keep "Hourly" as the default?

**Comment by pmaier1** [comment]
> @pmaier1 Fine for you? Keep "Hourly" as the default?

Great :+1: Yes, we should not change the default.

**Comment by VicDeo** [comment]
@micbar moved to the top of the list.
Screenshot: 
settings

**Comment by micbar** [comment]
@HanaGemela @jnweiger This needs a new release for the activity app.

**Comment by micbar** [comment]
@settermjd @pmaier1 We need to document that new setting and the new occ command.

**Comment by pmaier1** [comment]
> @settermjd @pmaier1 We need to document that new setting and the new occ command.

Please create a ticket.

**Comment by HanaGemela** [comment]
Documentation issue - https://github.com/owncloud/docs/issues/2388

**Comment by settermjd** [comment]
> @settermjd @pmaier1 We need to document that new setting and the new occ command.

Should have that done by the end of the week, @micbar.

**Comment by settermjd** [comment]
Is `activity:send-emails` the new occ command?

**Pull request merged**
