### PR TITLE
Revert back to the old method instead of the public one that tries to…

### PR DESCRIPTION
**Pull request by nickvergessen**
… read it

@enoch85 @deMattin please test

### CODE REVIEW

**Comment by enoch85** [comment]
I can't find display.php in the lib directory...

**Comment by nickvergessen** [comment]
That is in the lib/ of activity ;)

**Comment by enoch85** [comment]
@nickvergessen *doh* 'Of course. :) Will test this later tonight.

**Comment by enoch85** [comment]
@nickvergessen :+1:  on this! Tested and fixes the bug.

**Comment by nickvergessen** [comment]
> Analysing /home/travis/build/owncloud/core/apps/activity/lib/display.php
 1 errors
    line   94: OC_Helper - static method call on private class
App is not compliant

This breaks the code checker, but until a public method that is suitable has been added/backported, nothing we can do.

**Pull request merged**
