### PR TITLE
Set the formatting object so Extensions can adjust

### LINKED ISSUE #395: Reduce amount of text in activity sidebar, don’t show filename on every change
Currently in every single entry the filename is mentioned. This is way too much clutter in the sidebar where we don’t have much space and info should not be redundant anyway.
(Ignore the missing share icons please, that’s caused by my adblocker.)
capture du 2015-09-17 14-19-49
Here’s some better wording. Of course we can only use it here in the file-specific view, not in the Activity app.
capture du 2015-09-17 14-19-15

@owncloud/designers @nickvergessen

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Requires https://github.com/owncloud/core/pull/19522

Fix #395 

@MorrisJobke @PVince81 

---

Unit tests fail because of wrong core branch, CI branch at https://github.com/owncloud/activity/pull/403

### CODE REVIEW

**Comment by nickvergessen** [comment]
Unit tests fail because of wrong core branch, CI branch at https://github.com/owncloud/activity/pull/403

**Comment by PVince81** [comment]
It still says "You changed welcome.txt" in the sidebar. Is it intended ?
The sharing message however doesn't contain the file name any more.

**Comment by nickvergessen** [comment]
Yeah, I didn't change the self file actions, because "Changed", "Created" and so on dont make a lot of sense...

**Comment by PVince81** [comment]
Works :+1:

**Comment by MorrisJobke** [comment]
Works :+1:

**Pull request merged**
