### PR TITLE
[tests-only] Apply latest .drone.star quotes changes

### PR DESCRIPTION
**Pull request by phil-davis**
That were done in https://github.com/owncloud/search_elastic/pull/218

This makes consistent use of double-quotes for strings.

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingInt-master-firefox-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/activity/2062/21/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIDelRestore-master-firefox-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/activity/2062/19/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingInt-master-chrome-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/activity/2062/20/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIDelRestore-master-chrome-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/activity/2062/18/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUICreateUpdat-master-firefox-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/activity/2063/17/1

**Review by kiranparajuli589 — APPROVED** [review]

**Pull request merged**
