### PR TITLE
Reduce the number of 4000chars columns

### PR DESCRIPTION
**Pull request by nickvergessen**
@DeepDiver1975 for the MySQL 4byte work.
Does text(4000) to clob work on all dbms?

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> Does text(4000) to clob work on all dbms?

We have to test this

**Comment by nickvergessen** [comment]
Okay, will try to add one in core.

**Comment by LukasReschke** [comment]
I guess @butonic won't like you for that: https://github.com/owncloud/core/issues/23895#issuecomment-208184306 😉

**Comment by butonic** [comment]
:-1: find a better solution for oracle first

**Comment by nickvergessen** [comment]
Just saying in the activity app we never sort, search or whatever with these columns, only select via * is done.

**Comment by DeepDiver1975** [comment]
Using clob is valid from my pov - but the migration is tricky.
We also have to take into account that the activity table is hugh on some installations .....

**Comment by karlitschek** [comment]
This will make the upgrade from 9.0 to 9.1 slow. I'm not saying that we can't do that but we have to be careful. 
I also agree with @DeepDiver1975 and @butonic that this needs proper testing. Experience shows that there is a lot that can go wrong in corner-cases.

**Comment by nickvergessen** [comment]
So do we do this now, or one more version until people with 4byte mysql can use activity app?

**Comment by nickvergessen** [comment]
Oracle is unable to convert from text to clob atm, see https://github.com/owncloud/core/issues/24897
So if we don't want people to run some commands manually for the time-being, there is no way to do that.

**Pull request closed without merging**
