### PR TITLE
Fix activity fed user

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/24938

A bit convoluted but does the job.
Ideally at some point core should have an API to better distinguish a local user from a remote one.

@mmattel @DeepDiver1975  please review and test

### CODE REVIEW

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/25815 for a better API

**Comment by PVince81** [comment]
affected versions: stable9, stable9.1
not affected: stable8.2

**Comment by ppaysant** [comment]
Seems ok. :+1:

**Comment by PVince81** [comment]
stable9.1: https://github.com/owncloud/activity/pull/532
stable9: https://github.com/owncloud/activity/pull/533

**Pull request merged**
