### PR TITLE
[tests-only] [full-ci] add webUI tests to add owncloud server for a public link share

### PR DESCRIPTION
**Pull request by grgprarup**
## Description
Added a scenario to describe the activity generation when adding a server on a public link share.

## Related
- Part of https://github.com/owncloud/activity/issues/800
- Needs core PR https://github.com/owncloud/core/pull/40451 to be merged first

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingExt-master-firefox-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/activity/2985/23

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiActivity-master-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/activity/2985/24

**Review by kiranparajuli589 — COMMENTED** [review]
looks good.

**Review by saw-jan — COMMENTED** [review]
LGTM

**Review by SagarGi — COMMENTED** [review]
LGTM :+1:

**Review by SwikritiT — COMMENTED** [review]
Lgtm

**Review by individual-it — CHANGES_REQUESTED** [review]
generally looks good, but the test does not pass
```
WebUISharingContext::thePublicAddsThePublicLinkToUsingTheWebUI()

      Page\FilesPageBasic::waitTillPageIsLoaded timeout waiting for page to load (Exception)

**Comment by grgprarup** [comment]
> generally looks good, but the test does not pass
> 
> ```
> WebUISharingContext::thePublicAddsThePublicLinkToUsingTheWebUI()
> 
>       Page\FilesPageBasic::waitTillPageIsLoaded timeout waiting for page to load (Exception)
> ```

There is PR https://github.com/owncloud/core/pull/40451 that refactors this step, so need to merge that. I have added a new commit in this PR to check against that changes in core.

**Comment by individual-it** [comment]
#40451 is merged

**Review by individual-it — APPROVED** [review]

**Pull request merged**
