### PR TITLE
Limit file activities to favorites

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Depends on #276 
- [x] https://github.com/owncloud/core/pull/15196

### CODE REVIEW

**Comment by karlitschek** [comment]
@nickvergessen Can we merge this?:-)

**Comment by nickvergessen** [comment]
Not quite yet, but I will try to finish it today

**Comment by nickvergessen** [comment]
Should be ready, but the tests fail due to missing OC core changes of the linked PR.
So I added a second PR with a changed target branch: #277

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by MorrisJobke** [comment]
Core is now ready for this :)

**Comment by nickvergessen** [comment]
Since the fail happens when cleaning up after the test (can not delete the encryption key of the user when it was never created) which will be fixed by a core PR, im merging this.

**Pull request merged**
