### PR TITLE
[9.0] Fix displaying of the date in the sidebar

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #516 

1. Enable activity app
2. Create a new file
3. Open sidebar of the file
4. On the create activity try to find the date

### CODE REVIEW

**Comment by PVince81** [comment]
If not critical I'd prefer to get this into 9.0.3. Hopefully by then I'll get to review the linked PRs as well :smile:

**Comment by nickvergessen** [comment]
Wow, really? Uploading a file and opening the sidebar is too much being asked for?
3 lines changed (ignoring tests)...

The linked PR is much bigger atm, because it code depends on another PR...

**Comment by PVince81** [comment]
From what I see it is tagged as medium. We only merge PRs for 9.0.2 for critical/high issues especially this late.

Anyway, going to review your other PRs so we can move this forward.

**Comment by PVince81** [comment]
Tested, works :+1:

**Pull request merged**
