### PR TITLE
Dont try to delete items when no users in context

### PR DESCRIPTION
**Pull request by tomneedham**

### CODE REVIEW

**Comment by PVince81** [comment]
codecov not happy, need unit test update

**Comment by tomneedham** [comment]
Guessed so - just wanted to check it didn't kill anything else. On it.

**Comment by PVince81** [comment]
still on it ?

**Comment by tomneedham** [comment]
Updated the tests - let's wait for CI

**Comment by tomneedham** [comment]
Now codecov should be happy

**Comment by tomneedham** [comment]
rebased

**Pull request merged**
