### PR TITLE
Validate email

### PR DESCRIPTION
**Pull request by PVince81**
- [x] REQUIRES: https://github.com/owncloud/activity/pull/564 must be merged first

To be backported

@DeepDiver1975 FYI only the last commit

### CODE REVIEW

**Comment by PVince81** [comment]
- [ ] TODO: also add to `$processedUsers` when email address is empty to properly discard the entries

**Comment by PVince81** [comment]
rebased

**Comment by PVince81** [comment]
```
1) OCA\Activity\Tests\BackgroundJob\EmailNotificationTest::testRunStep

Expectation failed for method name is equal to <string:sendEmailToUser> when invoked 1 time(s).

Method was expected to be called 1 times, actually called 0 times.

/home/travis/build/owncloud/core/apps/activity/vendor/phpunit/phpunit/src/TextUI/Command.php:188

/home/travis/build/owncloud/core/apps/activity/vendor/phpunit/phpunit/src/TextUI/Command.php:118
```

**Comment by PVince81** [comment]
needs rethinking to fit in with https://github.com/owncloud/activity/issues/574

**Comment by PVince81** [comment]
@tomneedham does your other PR also cover invalid email addresses ? I see that we both added a catch block for exceptions. My PR might be obsolete then.

**Comment by tomneedham** [comment]
Yes it will catch the exception and log it, and continue for other users.

**Comment by tomneedham** [comment]
No pretty error message though :/

**Comment by PVince81** [comment]
closing as obsolete and I don't have time for this anyway

**Pull request closed without merging**
