### PR TITLE
Do not group remote users (they might be different users)

### PR DESCRIPTION
**Pull request by nickvergessen**
Non-local users are currently not distinguishable, so grouping them might
remove the information how many different users performed the same action.
So we do not group them anymore, until we found another solution.

Fixes owncloud/core#17569 

Although I think the problem is a different one, this helps to work around it. The grouping is useful and should be brought back, but first we need to be able to distinguish the different users.

@MorrisJobke please review

@karlitschek we shall backport this to 8.1 for the time being

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works with this patch :+1:

**Comment by MorrisJobke** [comment]
@gig13 Mind testing this?

**Comment by gig13** [comment]
@MorrisJobke 
I will test with OC8.0.5.

**Comment by MorrisJobke** [comment]
> I will test with OC8.0.5.

@nickvergessen Also mind a backport to stable8?

**Comment by karlitschek** [comment]
Great. :+1:  please backport

**Comment by nickvergessen** [comment]
Should be easily backportable once confirmed

**Comment by gig13** [comment]
@MorrisJobke @nickvergessen 
Let me know where to get the backport files, I tested with the ones above with OC8.0.5 and the Activity Stream just hung with the spinner.

**Comment by nickvergessen** [comment]
stable8.1 #334 
stable8.0 #335

**Comment by MorrisJobke** [comment]
@gig13 Backport for stable8 https://github.com/owncloud/activity/pull/335.patch

**Comment by gig13** [comment]
@MorrisJobke @nickvergessen 
Working in stable8.0

**Pull request merged**
